### ISSUE TITLE
Error When Running Burn-In Data

### ISSUE THREAD

**Issue by twaddlac** [benedictpaten/marginAlign#18]
Good day,

I am receiving an error when trying to run marginAlign with the default parameters. Below the command that I ran as well as the error report. Please let me know if you need any other information, thank you very much!

```
alan@zoidberg:~/projects/minion/lambda-burn-in/filtered-data/lambda-burn-in$ /opt/bioinformatics-software/minion-software/margin/marginAlign first-run.passed.fastq ../../lamda-phage.fasta first.passed.sam
Got message from job at time: 1429552015.62 : Going to chain sam file: /home/alan/projects/minion/lambda-burn-in/filtered-data/lambda-burn-in/jobTree/jobs/gTD0/tmp_4vbY30VFrP/temp.sam
Got message from job at time: 1429552015.62 : Going to realign sam file: /home/alan/projects/minion/lambda-burn-in/filtered-data/lambda-burn-in/jobTree/jobs/gTD1/tmp_pxHowcXufF/temp.sam to create output sam file: first.passed.sam     with match gamma 0.5 and gap gamma 0.0 and model /opt/bioinformatics-software/minion-software/margin/src/margin/mappers/last_hmm_20.txt
The job seems to have left a log file, indicating failure: /home/alan/projects/minion/lambda-burn-in/filtered-data/lambda-burn-in/jobTree/jobs/job
Reporting file: /home/alan/projects/minion/lambda-burn-in/filtered-data/lambda-burn-in/jobTree/jobs/log.txt
log.txt:        ---JOBTREE SLAVE OUTPUT LOG---
log.txt:        Traceback (most recent call last):
log.txt:          File "/opt/bioinformatics-software/minion-software/margin/submodules/jobTree/src/jobTreeSlave.py", line 271, in main
log.txt:            defaultMemory=defaultMemory, defaultCpu=defaultCpu, depth=depth)
log.txt:          File "/opt/bioinformatics-software/minion-software/margin/submodules/jobTree/scriptTree/stack.py", line 153, in execute
log.txt:            self.target.run()
log.txt:          File "/opt/bioinformatics-software/minion-software/margin/submodules/jobTree/scriptTree/target.py", line 197, in run
log.txt:            func(*((self,) + tuple(self.args)), **self.kwargs)
log.txt:          File "/opt/bioinformatics-software/minion-software/margin/src/margin/marginAlignLib.py", line 345, in realignSamFile3TargetFn
log.txt:            ops += map(lambda op : (op.type, op.length), pA.operationList)
log.txt:        AttributeError: 'NoneType' object has no attribute 'operationList'
log.txt:        Exiting the slave because of a failed job on host zoidberg
log.txt:        Due to failure we are reducing the remaining retry count of job /home/alan/projects/minion/lambda-burn-in/filtered-data/lambda-burn-in/jobTree/jobs/job to 0
log.txt:        We have set the default memory of the failed job to 2147483648 bytes
Job: /home/alan/projects/minion/lambda-burn-in/filtered-data/lambda-burn-in/jobTree/jobs/job is completely failed
Traceback (most recent call last):
  File "/opt/bioinformatics-software/minion-software/margin/src/margin/marginAlign.py", line 91, in <module>
    main()
  File "/opt/bioinformatics-software/minion-software/margin/src/margin/marginAlign.py", line 87, in main
    raise RuntimeError("Got failed jobs")
RuntimeError: Got failed jobs
```

**Comment by benedictpaten** [comment]
Sorry for the hassle. I pushed a v0.1 release last night. Can you confirm
you are using this (i.e. that you've updated your distribution according to
the instructions on the website / checked-out a fresh distribution)? Also,
are you using the virtual-env?

**Comment by twaddlac** [comment]
Yes, I am using the most recent version, and no I am not using a virtual
environment. I checked out the newest distro yesterday afternoon with no
avail.

On Mon, Apr 20, 2015 at 3:12 PM, Benedict Paten notifications@github.com
wrote:

> Sorry for the hassle. I pushed a v0.1 release last night. Can you confirm
> you are using this (i.e. that you've updated your distribution according to
> the instructions on the website / checked-out a fresh distribution)? Also,
> are you using the virtual-env?
> 
> On Mon, Apr 20, 2015 at 10:54 AM, twaddlac notifications@github.com
> wrote:
> 
> > Good day,
> > 
> > I am receiving an error when trying to run marginAlign with the default
> > parameters. Below the command that I ran as well as the error report.
> > Please let me know if you need any other information, thank you very
> > much!
> > 
> > alan@zoidberg:~/projects/minion/lambda-burn-in/filtered-data/lambda-burn-in$
> > /opt/bioinformatics-software/minion-software/margin/marginAlign
> > first-run.passed.fastq ../../lamda-phage.fasta first.passed.sam
> > Got message from job at time: 1429552015.62 : Going to chain sam file:
> > /home/alan/projects/minion/lambda-burn-in/filtered-data/lambda-burn-in/jobTree/jobs/gTD0/tmp_4vbY30VFrP/temp.sam
> > Got message from job at time: 1429552015.62 : Going to realign sam file:
> > /home/alan/projects/minion/lambda-burn-in/filtered-data/lambda-burn-in/jobTree/jobs/gTD1/tmp_pxHowcXufF/temp.sam
> > to create output sam file: first.passed.sam with match gamma 0.5 and gap
> > gamma 0.0 and model
> > /opt/bioinformatics-software/minion-software/margin/src/margin/mappers/last_hmm_20.txt
> > The job seems to have left a log file, indicating failure:
> > /home/alan/projects/minion/lambda-burn-in/filtered-data/lambda-burn-in/jobTree/jobs/job
> > Reporting file:
> > /home/alan/projects/minion/lambda-burn-in/filtered-data/lambda-burn-in/jobTree/jobs/log.txt
> > log.txt: ---JOBTREE SLAVE OUTPUT LOG---
> > log.txt: Traceback (most recent call last):
> > log.txt: File
> > "/opt/bioinformatics-software/minion-software/margin/submodules/jobTree/src/jobTreeSlave.py",
> > line 271, in main
> > log.txt: defaultMemory=defaultMemory, defaultCpu=defaultCpu, depth=depth)
> > log.txt: File
> > "/opt/bioinformatics-software/minion-software/margin/submodules/jobTree/scriptTree/stack.py",
> > line 153, in execute
> > log.txt: self.target.run()
> > log.txt: File
> > "/opt/bioinformatics-software/minion-software/margin/submodules/jobTree/scriptTree/target.py",
> > line 197, in run
> > log.txt: func(_((self,) + tuple(self.args)), *_self.kwargs)
> > log.txt: File
> > "/opt/bioinformatics-software/minion-software/margin/src/margin/marginAlignLib.py",
> > line 345, in realignSamFile3TargetFn
> > log.txt: ops += map(lambda op : (op.type, op.length), pA.operationList)
> > log.txt: AttributeError: 'NoneType' object has no attribute
> > 'operationList'
> > log.txt: Exiting the slave because of a failed job on host zoidberg
> > log.txt: Due to failure we are reducing the remaining retry count of job
> > /home/alan/projects/minion/lambda-burn-in/filtered-data/lambda-burn-in/jobTree/jobs/job
> > to 0
> > log.txt: We have set the default memory of the failed job to 2147483648
> > bytes
> > Job:
> > /home/alan/projects/minion/lambda-burn-in/filtered-data/lambda-burn-in/jobTree/jobs/job
> > is completely failed
> > Traceback (most recent call last):
> > File
> > "/opt/bioinformatics-software/minion-software/margin/src/margin/marginAlign.py",
> > line 91, in <module>
> > main()
> > File
> > "/opt/bioinformatics-software/minion-software/margin/src/margin/marginAlign.py",
> > line 87, in main
> > raise RuntimeError("Got failed jobs")
> > RuntimeError: Got failed jobs
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/benedictpaten/marginAlign/issues/18.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/benedictpaten/marginAlign/issues/18#issuecomment-94544441
> .

## 

Alan

**Comment by benedictpaten** [comment]
Hi, it seems like an odd corner case. Is it possible for you to send me
your input files to test? I'm not sure I can work out what's going on from
the error alone. Sorry for the hassle,

Benedict
(from phone)

**Comment by twaddlac** [comment]
Sorry for the delayed response, one of the latest pulls fixed the issue. Thanks for you help!
