### ISSUE TITLE
no mapping quality in final Sam file

### ISSUE THREAD

**Issue by lfaino** [benedictpaten/marginAlign#19]
Hi all,
I have an issue when I run marginAlign. The first sam file contains the mapping quality (all of them are 255) while the last sam file all the quality goes to 0. how can I fix this problem? are you thinking to fix in a next release?

thanks
Luigi

**Comment by mitenjain** [comment]
Hi Luigi,

We are planning on including a BAQ type score in the next release. This is coming shortly, over the next few weeks.

Thank you.

Best regards,
Miten
