### ISSUE TITLE
marginCaller - no such file 'posteriorProbs.txt'

### ISSUE THREAD

**Issue by demharters** [benedictpaten/marginAlign#21]
When trying to call SNVs with marginCaller the programme crashes and I get the following output (I am only posting one instance of many identical messages):

**Mac OS X (El Capitan):**
$ marginCaller input.sam reference.fasta output.vcf
/Users/sam/software/marginAlign/src/margin/mappers/last_hmm_20.txt
0.3
The job seems to have left a log file, indicating failure: /Users/sam/jobTree/jobs/t3/t2/job
Reporting file: /Users/sam/jobTree/jobs/t3/t2/log.txt
log.txt:    ---JOBTREE SLAVE OUTPUT LOG---
log.txt:    /bin/sh: 939732440: command not found
log.txt:    /bin/sh: gb: command not found
log.txt:    /bin/sh: CP011343.2: command not found
log.txt:    /bin/sh: 2403236: command not found
log.txt:    Traceback (most recent call last):
log.txt:      File "/Users/sam/software/marginAlign/submodules/jobTree/src/jobTreeSlave.py", line 271, in main
log.txt:        defaultMemory=defaultMemory, defaultCpu=defaultCpu, depth=depth)
log.txt:      File "/Users/sam/software/marginAlign/submodules/jobTree/scriptTree/stack.py", line 153, in execute
log.txt:        self.target.run()
log.txt:      File "/Users/sam/software/marginAlign/submodules/jobTree/scriptTree/target.py", line 197, in run
log.txt:        func(_((self,) + tuple(self.args)), *_self.kwargs)
log.txt:      File "/Users/sam/software/marginAlign/src/margin/marginCallerLib.py", line 61, in posteriorProbabilityCalculationTargetFn
log.txt:        map(lambda x : map(float, x.split()), open(tempPosteriorProbsFile, 'r')):
log.txt:    IOError: [Errno 2] No such file or directory: '/var/folders/lr/ws3f8_kd2p343vqcrj36w7z40000gn/T/tmpomTYBS/localTempDir/posteriorProbs.txt'
log.txt:    Exiting the slave because of a failed job on host Macbook
log.txt:    Due to failure we are reducing the remaining retry count of job /Users/sam/jobTree/jobs/t3/t2/job to 0
log.txt:    We have set the default memory of the failed job to 2147483648 bytes
Job: /Users/sam/jobTree/jobs/t3/t2/job is completely failed

**Linux (Red Hat Enterprise Linux Server release 6.3 (Santiago)):**
$ marginCaller output.sam referenceBC01.fasta output.vcf
/home/coml-nmsi/sdemharter/software/marginAlign/src/margin/mappers/last_hmm_20.txt
0.3
The job seems to have left a log file, indicating failure: /data/coml-nmsi/sdemharter/ont/jobTree/jobs/t0/t0/t1/job
Reporting file: /data/coml-nmsi/sdemharter/ont/jobTree/jobs/t0/t0/t1/log.txt
log.txt:        ---JOBTREE SLAVE OUTPUT LOG---
log.txt:        /bin/sh: gb: command not found
log.txt:        /bin/sh: 173474: command not found
log.txt:        /bin/sh: CP011343.2: command not found
log.txt:        /bin/sh: 939732440: command not found
log.txt:        Traceback (most recent call last):
log.txt:          File "/home/coml-nmsi/sdemharter/software/marginAlign/submodules/jobTree/src/jobTreeSlave.py", line 271, in main
log.txt:            defaultMemory=defaultMemory, defaultCpu=defaultCpu, depth=depth)
log.txt:          File "/home/coml-nmsi/sdemharter/software/marginAlign/submodules/jobTree/scriptTree/stack.py", line 153, in execute
log.txt:            self.target.run()
log.txt:          File "/home/coml-nmsi/sdemharter/software/marginAlign/submodules/jobTree/scriptTree/target.py", line 197, in run
log.txt:            func(_((self,) + tuple(self.args)), *_self.kwargs)
log.txt:          File "/home/coml-nmsi/sdemharter/software/marginAlign/src/margin/marginCallerLib.py", line 62, in posteriorProbabilityCalculationTargetFn
log.txt:            map(lambda x : map(float, x.split()), open(tempPosteriorProbsFile, 'r')):
log.txt:        IOError: [Errno 2] No such file or directory: '/tmp/tmpX__aXV/localTempDir/posteriorProbs.txt'
log.txt:        Exiting the slave because of a failed job on host login3
log.txt:        Due to failure we are reducing the remaining retry count of job /data/coml-nmsi/sdemharter/ont/jobTree/jobs/t0/t0/t1/job to 0
log.txt:        We have set the default memory of the failed job to 2147483648 bytes
Job: /data/coml-nmsi/sdemharter/ont/jobTree/jobs/t0/t0/t1/job is completely failed

**Comment by mitenjain** [comment]
The marginCaller module was crashing due to special characters in fasta file. I am fixing it on a branch, and will update this.

**Comment by mitenjain** [comment]
Need to fix ASAP

**Comment by mitenjain** [comment]
This should be fixed now.
