### ISSUE TITLE
Reference fasta file

### ISSUE THREAD

**Issue by icymiktreize** [benedictpaten/marginAlign#22]
Hi,
I managed to map my FASTQ file with human genome with marginAlign. When trying with reference fasta file I created, it did not work. This file contains IUPAC code beside A; T; G; C. I just wonder if that's the problem.
Cheers

**Comment by mitenjain** [comment]
Hello,

Sorry for the delay. Currently, marginAlign does not support nucleotide letters besides A's, C's, G's, and T's. We are working on adding some support on this in the next release.

Thank you.
