### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by bsipos** [benedictpaten/marginAlign#27]
I get the following compilation error on Ubuntu 14.04:

`
...
cp CuTest.h ../../lib/
make[4]: Leaving directory`/opt/marginAlign/submodules/sonLib/externalTools/cutest'
make[3]: Leaving directory `/opt/marginAlign/submodules/sonLib/externalTools'
make[2]: Leaving directory`/opt/marginAlign/submodules/sonLib'
make[1]: **\* [all.sonLib] Error 2
make[1]: **\* Waiting for unfinished jobs....
impl/pairwiseAligner.c:15:20: fatal error: bioioC.h: No such file or directory
 #include "bioioC.h"
                    ^
compilation terminated.
CA_code/lambda_calculator.c: In function 'Find_JP':
CA_code/lambda_calculator.c:371:17: warning: 'flag_sign' may be used uninitialized in this function [-Wmaybe-uninitialized]
       Sum_local = Nail_lambda(mat_b, flag_sign, lambda_min, lambda_max, p,q, &lambda_final);
                 ^
gcc -Wall -O2  -o last-merge-batches last-merge-batches.o
bwashm.c: In function 'bwa_shm_stage':
bwashm.c:29:11: warning: ignoring return value of 'ftruncate', declared with attribute warn_unused_result [-Wunused-result]
  ftruncate(shmid, BWA_CTL_SIZE);
           ^
bwashm.c:66:11: warning: ignoring return value of 'ftruncate', declared with attribute warn_unused_result [-Wunused-result]
  ftruncate(shmid, idx->l_mem);
           ^
impl/stateMachine.c:13:20: fatal error: bioioC.h: No such file or directory
 #include "bioioC.h"
                    ^
compilation terminated.
make[2]: Leaving directory `/opt/marginAlign/submodules/cPecan'
make[2]: *** [../sonLib/lib/cPecanLib.a] Error 1
make[1]: *** [all.cPecan] Error 2
g++ -O3  -o lastdb Alphabet.o MultiSequence.o CyclicSubsetSeed.o SubsetSuffixArray.o LastdbArguments.o io.o fileMap.o SubsetSuffixArraySort.o MultiSequenceQual.o lastdb.o
g++ -O3  -o lastex Alphabet.o LastexArguments.o io.o ScoreMatrix.o lastex.o gumbel_params/mcf_local_alignment_evaluer.o gumbel_params/njn_dynprogprob.o gumbel_params/njn_dynprogproblim.o gumbel_params/njn_dynprogprobproto.o gumbel_params/njn_ioutil.o gumbel_params/njn_localmaxstat.o gumbel_params/njn_localmaxstatmatrix.o gumbel_params/njn_localmaxstatutil.o gumbel_params/njn_matrix.o gumbel_params/random_gen.o gumbel_params/sls_alp.o gumbel_params/sls_alp_data.o gumbel_params/sls_alp_regression.o gumbel_params/sls_alp_sim.o gumbel_params/sls_pvalues.o
g++ -O3  -o last-split Alphabet.o MultiSequence.o fileMap.o split/cbrc_linalg.o split/last-split.o split/cbrc_split_aligner.o split/last-split-main.o split/cbrc_unsplit_alignment.o
g++ -O3  -o lastal Alphabet.o MultiSequence.o CyclicSubsetSeed.o SubsetSuffixArray.o LastalArguments.o io.o fileMap.o ScoreMatrix.o DiagonalTable.o SegmentPair.o Alignment.o GappedXdropAligner.o SegmentPairPot.o AlignmentPot.o GeneralizedAffineGapCosts.o Centroid.o LambdaCalculator.o TwoQualityScoreMatrix.o OneQualityScoreMatrix.o QualityPssmMaker.o GeneticCode.o gaplessXdrop.o gaplessPssmXdrop.o gaplessTwoQualityXdrop.o AlignmentWrite.o MultiSequenceQual.o GappedXdropAlignerPssm.o GappedXdropAligner2qual.o GappedXdropAligner3frame.o lastal.o CA_code/lambda_calculator.o
make[3]: Leaving directory`/opt/marginAlign/submodules/last/src'
make[2]: Leaving directory `/opt/marginAlign/submodules/last'
ar -csru libbwa.a utils.o kthread.o kstring.o ksw.o bwt.o bntseq.o bwa.o bwamem.o bwamem_pair.o bwamem_extra.o malloc_wrap.o
gcc -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS QSufSort.o bwt_gen.o bwashm.o bwase.o bwaseqio.o bwtgap.o bwtaln.o bamlite.o is.o bwtindex.o bwape.o kopen.o pemerge.o maxk.o bwtsw2_core.o bwtsw2_main.o bwtsw2_aux.o bwt_lite.o bwtsw2_chain.o fastmap.o bwtsw2_pair.o main.o -o bwa -L. -lbwa -lm -lz -lpthread -lrt
make[2]: Leaving directory`/opt/marginAlign/submodules/bwa'
make[1]: Leaving directory `/opt/marginAlign/submodules'
make: *** [all] Error 2
`

Any suggestions how to fix this?

**Comment by mitenjain** [comment]
Sorry for the hassle. Could you check if you have Ubuntu-appropriate zlib and libxml and libxzlt installed?

I checked the install and it worked for me in Ubuntu 16.10. I did have to install zlib1g-dev, python-dev, libxml2-dev, and libxslt-dev.

Could you try installing from scratch again with these installs in place? 

Thank you.

**Comment by bsipos** [comment]
Problem solved, it was not caused by missing dependencies: it seems if I try to compile it with "make -j" then it fails as above, but it compiles fine with just "make".

**Comment by mitenjain** [comment]
Thank you. Let us know if you get any other issues.
