### ISSUE TITLE
Make test fails

### ISSUE THREAD

**Issue by Ubsam** [benedictpaten/marginAlign#30]
Hey Benedict,

After successfully completing all the previous steps in a UNIX server environment (remote login) the make test stage results in Failure, with 10/17 errors.

Not entirely sure what might have gone wrong. Tried troubleshooting by performing all steps inside the environment first, no luck there, currently trying to see if setting the path shortcuts fixes the issue.

**Comment by mitenjain** [comment]
Hello,

Are you using virtualenv? Could you send me the error messages so I Can try and reproduce them on our end. My email is miten@soe.ucsc.edu

Sorry for the hassle.
-Miten, Benedict

**Comment by Ubsam** [comment]
Of course I can! I am using anaconda to create a virtual environment. I will email you the error messages ASAP, the error seems to be the same for all of them:

AttributeError: ReadAlignmentStats instance has no attribute 'identity'

Except the last one (testMarginStats)
Traceback (most recent call last):
  File "./tests/tests.py", line 208, in testMarginStats
    (self.marginStats, self.inputSamFile1, self.readFastqFile1, self.referenceFastaFile1))
  File "/sfs/lustre/scratch/sp3cy/margin/marginAlign/submodules/sonLib/bioio.py", line 184, in system
    raise RuntimeError("Command: %s exited with non-zero status %i" % (command, sts))
RuntimeError: Command: /sfs/lustre/scratch/sp3cy/margin/marginAlign/marginStats /sfs/lustre/scratch/sp3cy/margin/marginAlign/tests/input.sam /sfs/lustre/scratch/sp3cy/margin/marginAlign/tests/lessReads.fq /sfs/lustre/scratch/sp3cy/margin/marginAlign/tests/references.fa --identity --mismatchesPerAlignedBase --readCoverage         --deletionsPerReadBase --insertionsPerReadBase --printValuePerReadAlignment exited with non-zero status 2

**Comment by mitenjain** [comment]
Hello,

Apologies. I had forgotten to update the tests. If you did a git pull and then re-ran tests, they should now work.

Please let us know if this resolves the problem.

**Comment by Ubsam** [comment]
This resolved the problem! All 17 tests passed :)

Time for me to actually start using the program!
