### ISSUE TITLE
marginAlign & marginCaller errors

### ISSUE THREAD

**Issue by amnaniamin** [benedictpaten/marginAlign#32]
Hi,

I'm using Ubuntu 16.04 LTS on virtualbox. I got the following error when running marginAlign for Nanopore reads. 

> ---JOBTREE SLAVE OUTPUT LOG---
> Traceback (most recent call last):
>   File "/home/ewc/marginAlign/submodules/jobTree/src/jobTreeSlave.py", line 271, in main
>     defaultMemory=defaultMemory, defaultCpu=defaultCpu, depth=depth)
>   File "/home/ewc/marginAlign/submodules/jobTree/scriptTree/stack.py", line 153, in execute
>     self.target.run()
>   File "/home/ewc/marginAlign/src/margin/mappers/last.py", line 35, in run
>     Last.run(self)
>   File "/home/ewc/marginAlign/src/margin/mappers/last.py", line 19, in run
>     for name, seq, quals in fastqRead(self.readFastqFile):
>   File "/home/ewc/marginAlign/submodules/sonLib/bioio.py", line 769, in fastqRead
>     raise RuntimeError("Got a qual value out of range %s (range is 33 to 126)" % i)
> RuntimeError: Got a qual value out of range 13 (range is 33 to 126)
> Exiting the slave because of a failed job on host ewc-VirtualBox
> Due to failure we are reducing the remaining retry count of job /media/sf_MinION_Pipeline/jobTree/jobs/job to 0
> We have set the default memory of the failed job to 2147483648.0 bytes

Then, I also got the following error when running marginCaller for SAM file (aligned using BWA-MEM). 

> ---JOBTREE SLAVE OUTPUT LOG---
> Traceback (most recent call last):
>   File "/home/ewc/marginAlign/submodules/jobTree/src/jobTreeSlave.py", line 271, in main
>     defaultMemory=defaultMemory, defaultCpu=defaultCpu, depth=depth)
>   File "/home/ewc/marginAlign/submodules/jobTree/scriptTree/stack.py", line 153, in execute
>     self.target.run()
>   File "/home/ewc/marginAlign/submodules/jobTree/scriptTree/target.py", line 197, in run
>     func(*((self,) + tuple(self.args)), **self.kwargs)
>   File "/home/ewc/marginAlign/src/margin/marginCallerLib.py", line 211, in variantCallSamFileTargetFn
>     evolutionarySubstitutionMatrix, errorSubstitutionMatrix)
>   File "/home/ewc/marginAlign/src/margin/marginCallerLib.py", line 89, in calcBasePosteriorProbs
>     observedBase))*baseObservations[observedBase], BASES)), BASES)
>   File "/home/ewc/marginAlign/src/margin/marginCallerLib.py", line 86, in <lambda>
>     math.log(getProb(evolutionarySubstitionMatrix, refBase.upper(), missingBase)) +
>   File "/home/ewc/marginAlign/src/margin/marginCallerLib.py", line 79, in getProb
>     return subMatrix[(start, end)]
> KeyError: ('N', 'A')
> Exiting the slave because of a failed job on host ewc-VirtualBox
> Due to failure we are reducing the remaining retry count of job /media/sf_MinION_Pipeline/jobTree/jobs/job to 0
> We have set the default memory of the failed job to 2147483648 bytes
> ount of job /media/sf_MinION_Pipeline/jobTree/jobs/job to 0
> We have set the default memory of the failed job to 2147483648 bytes

What should i do to solve the issues? 

Thanks.

**Comment by mitenjain** [comment]
For issue 1, how was the fastq file generated? If you could send a test example to miten@soe.ucsc.edu, I can try reproducing the issue at our end and push a fix.

Issue 2 seems to have arisen due to the presence of "N" in the reference fasta file. If you replace the "N"s in the file and re-run, ti should work. I need to put in a workaround for this (WIP). 

Apologies for the hassle.
-Miten & Benedict

**Comment by mitenjain** [comment]
Hi there, just checking in if this issue is resolved for you?

**Comment by maximus-sci** [comment]
Hello,

I'm getting the first error that the OP posted:
```
raise RuntimeError("Got a qual value out of range %s (range is 33 to 126)" % i)
RuntimeError: Got a qual value out of range 13 (range is 33 to 126)
```

What does this error mean? I can email one of the fasta files to someone if that will help...

**Comment by mitenjain** [comment]
A MWE would help. Could you email it to miten@soe.ucsc.edu?
