### ISSUE TITLE
marginAlign: command not found

### ISSUE THREAD

**Issue by cliu32** [benedictpaten/marginAlign#34]
I followed the instructions and everything seems to be fine up to "make test". It was successful without using the virtualenv. And then when I tried to call marginAlign, I got "command not found". Not sure what I missed and I'd appreciate any help. Many thanks!

**Comment by mitenjain** [comment]
Hello,

Are you giving the entire /path/to/marginAlign or is marginAlign added to your default path? We recommend using virtualenv because it encompasses all dependencies.

Best regards,
Miten

**Comment by cliu32** [comment]
Thanks for the response! I could not call it when I was in the margin base directory. I can see marginAlign right there, and the make test worked well without the virtualenv. Any thoughts?

Chang

**Comment by mitenjain** [comment]
Have you tried running it as ./marginAlign from the base? That may force the executable.

**Comment by cliu32** [comment]
./marginAlign works. Thank you!
