### ISSUE TITLE
make test fail

### ISSUE THREAD

**Issue by LotusWang0723** [benedictpaten/marginAlign#36]
After I run make test, it is reported that there is no vcf module

File "./tests/tests.py", line 4, in <module>
    from margin.marginCallerLib import vcfRead
  File "/data/ltwang/software/marginAlign/src/margin/marginCallerLib.py", line 1, in <module>
    import pysam, sys, os, collections, vcf, datetime
ImportError: No module named vcf
Makefile:5: recipe for target 'test' failed
make: *** [test] Error 1

how can I solve this problem?

**Comment by mitenjain** [comment]
Hello,

Are you using a virtualenv? That will allow you to contain all dependencies (listed in requirement.txt).

Thank you.

**Comment by LotusWang0723** [comment]
Thanks a lot. I forgot to use virtualenv. Now make test can run correctly.
