### ISSUE TITLE
Error: sees to be looking for enriron.pickle at the wrong location

### ISSUE THREAD

**Issue by cliu32** [benedictpaten/marginAlign#38]
Hi, I was trying to run the basic command line: marginAlign fastqfile fastaRef test.sam --jobTree ./jobTree but ran into the following error message and the program stalled. 
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/username/exp/marginAlign/submodules/jobTree/batchSystems/singleMachine.py", line 51, in worker
    slaveMain()
  File "/home/username/exp/marginAlign/submodules/jobTree/src/jobTreeSlave.py", line 103, in main
    fileHandle = open(getEnvironmentFileName(jobTreePath), 'r')
IOError: **[Errno 2] No such file or directory: '/media/username/Seagate/environ.pickle'**
I could not understand the error message becuase I was running the program at this location '/media/username/Seagate Backup Plus Drive/ONTreads/experiment1207/testmargin/' and I can see the jobTree folder created there. But the program seems to be looking for environ.pickle at  '/media/username/Seagate/'. 
How can I fix this problem? Thank you so much for your help!

**Comment by mitenjain** [comment]
Hello,

Are you using a virtualenv? If not, could you try using it? 

If you could send me some test data I can try and reproduce the error on our end. This will help us debug the issue.

Thank you.

**Comment by cliu32** [comment]
Thanks for the quick response. I moved the job from my external hard drive to the internal hard drive, and the problem disappeared. But I got the following error message: 
log.txt:	---JOBTREE SLAVE OUTPUT LOG---
log.txt:	lastdb: bad symbol: -
I do have '-' in my fasta reference file as spacerholders between two exons. Is there a way to keep these placeholders? Thanks and happy new year.

**Comment by mitenjain** [comment]
There isn't at the moment I am afraid. You could substitute that with an N and bwa will align it (I think minimap2 will as well). Not sure how that plays with downstream processing since marginAlign presently isn't compatible with the splice-aware CIGAR strings.
