### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by mbhall88** [benedictpaten/marginAlign#39]
Hi,
I was wondering if you might be able to help me decrypt this error message?
I am have the most recent release version 0.1. This job was run with the command 
```sh
marginAlign input.fastq ref.fa marginAlign.sam --em --outputModel output.hmm \
    --jobTree ./jobTree --maxThreads=16
```
It was run on a cluster node with 50GB memory allocated and 16 CPUs. The job failed with message:
```
---JOBTREE SLAVE OUTPUT LOG---
Traceback (most recent call last):
  File "/nfs/research1/zi/mbhall/Software/marginAlign/submodules/jobTree/src/jobTreeSlave.py", line 271, in main
    defaultMemory=defaultMemory, defaultCpu=defaultCpu, depth=depth)
  File "/nfs/research1/zi/mbhall/Software/marginAlign/submodules/jobTree/scriptTree/stack.py", line 153, in execute
    self.target.run()
  File "/nfs/research1/zi/mbhall/Software/marginAlign/src/margin/mappers/last.py", line 35, in run
    Last.run(self)
  File "/nfs/research1/zi/mbhall/Software/marginAlign/src/margin/mappers/last.py", line 20, in run
    fastaWrite(fH, name, seq)
  File "/nfs/research1/zi/mbhall/Software/marginAlign/submodules/sonLib/bioio.py", line 746, in fastaWrite
    fileHandle.write("%s\n" % seq[i:i+chunkSize])
IOError: [Errno 28] No space left on device
Exiting the slave because of a failed job on host hx-noah-02-04.ebi.ac.uk
Due to failure we are reducing the remaining retry count of job /hps/nobackup/research/zi/mbhall/Aligner_test/jobTree/jobs/job to 0
We have set the default memory of the failed job to 2147483648.0 bytes
```
I am assuming `IOError: [Errno 28] No space left on device` is the clue. Just not sure if it is alluding to memory or disk space? I could throw more memory at it if need be but 50GB seems like a fair bit already. There's also more than enough disk space on the cluster for the job so I am assuming this is not the case.  
Cheers.

**Comment by mitenjain** [comment]
Sorry for the delay. This seems like a memory issue. Have you tried the memory option using jobTree as well? That may help. 

We also have a toil version of marginAlign if you'd like to try that. The documentation in that one is in need of a substantial overhaul, but I could help you running with it if you want.

**Comment by mbhall88** [comment]
Sorry, forgot about this. Ended up figuring it out but needed a HUGE amount of RAM.   
I'll keep the other version in mind for future and get in touch if need be.  
Thanks!
