### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by herrroaa** [benedictpaten/marginAlign#41]
Hi,
I installed marginAlign, I did a test run (make test) and it was successful, please see below the final part of the test run result.
However, when I try to call marginAlign it returns
`-bash: marginAlign: command not found`

`.AverageReadIdentity 0.795369618446
MedianReadIdentity 0.795369618446
MinReadIdentity 0.720926843486
MaxReadIdentity 0.869812393405
ValuesReadIdentity 0.869812393405	0.720926843486
AverageAlignmentIdentity 0.509266537938
MedianAlignmentIdentity 0.509266537938
MinAlignmentIdentity 0.417804478427
MaxAlignmentIdentity 0.60072859745
ValuesAlignmentIdentity 0.417804478427	0.60072859745
AverageReadCoverage 0.901063009589
MedianReadCoverage 0.901063009589
MinReadCoverage 0.860682016905
MaxReadCoverage 0.941444002274
ValuesReadCoverage 0.941444002274	0.860682016905
AverageMismatchesPerAlignedBase 0.119232100001
MedianMismatchesPerAlignedBase 0.119232100001
MinMismatchesPerAlignedBase 0.0760869565217
MaxMismatchesPerAlignedBase 0.162377243481
ValuesMismatchesPerAlignedBase 0.0760869565217	0.162377243481
AverageDeletionsPerReadBase 0.0574880045021
MedianDeletionsPerReadBase 0.0574880045021
MinDeletionsPerReadBase 0.0458937198068
MaxDeletionsPerReadBase 0.0690822891974
ValuesDeletionsPerReadBase 0.0458937198068	0.0690822891974
AverageInsertionsPerReadBase 0.0392299405665
MedianInsertionsPerReadBase 0.0392299405665
MinInsertionsPerReadBase 0.0386048086692
MaxInsertionsPerReadBase 0.0398550724638
ValuesInsertionsPerReadBase 0.0398550724638	0.0386048086692
.
----------------------------------------------------------------------
Ran 19 tests in 72.898s

OK
`

**Comment by mitenjain** [comment]
Hello,

Are you running the executable from the marginAlign directory itself? If so, you'll probably need to run it as ./marginAlign. Could you check and try this?

Thank you.

**Comment by herrroaa** [comment]
Hi,
It seems to work after trying ./marginAlign.
Can I know why it worked after using this hidden file while it did not when I used the executable marginAlign?
Also can I use marginCaller with bam files generated using any other aligners (as for example minimap2 / bwa)? 

Thanks a lot

**Comment by mitenjain** [comment]
When you are in the base directory, you are specifying the executable by using the ./. If you add marginAlign to your $PATH then you won't need to do this. 
At this moment, marginAlign works with a SAM files that could have been generated by any aligner (LAST, BLASR, LASTZ, BWA, minimap2, GraphMap etc.). I will try and bring in BAM compatibility in short order. 

Hope this helps. Let me know as you have more questions.
