### ISSUE TITLE
RuntimeError - "expected three arguments"

### ISSUE THREAD

**Issue by nadakubikova** [benedictpaten/marginAlign#44]
Hi, 

I am running into problem when trying to execute marginAlign. Has anybody got any idea about the error message I got? I am new in this community. This is what I ran:

(env) Nadas-MBP:marginAlign nadakubikova$ ./marginAlign /Users/nadakubikova/Documents/Sequenced\ Data/fastq_First\ Nanopore\ Run/downloads/PASS/BC01/BC01_trimmed.fastq /Users/nadakubikova/Documents/Sequenced\ Data/fastq_First\ Nanopore\ Run/downloads/PASS/BC01/chr1.fa /Users/nadakubikova/Documents/Sequenced\ Data/fastq_First\ Nanopore\ Run/downloads/PASS/BC01/BC01_trimmed.sam --jobTree ./jobTree
Traceback (most recent call last):
  File "./src/margin/marginAlign.py", line 109, in <module>
    main()
  File "/Users/nadakubikova/marginAlign/src/margin/marginAlign.py", line 72, in main
    raise RuntimeError("Expected three arguments, got: %s" % " ".join(args))
**RuntimeError: Expected three arguments, got:** /Users/nadakubikova/Documents/Sequenced Data/fastq_First Nanopore Run/downloads/PASS/BC01/BC01_trimmed.fastq /Users/nadakubikova/Documents/Sequenced Data/fastq_First Nanopore Run/downloads/PASS/BC01/chr1.fa /Users/nadakubikova/Documents/Sequenced Data/fastq_First Nanopore Run/downloads/PASS/BC01/BC01_trimmed.sam

I would be grateful for any suggestions. 
Thanks, 
N

**Comment by mitenjain** [comment]
Hello,

Could you remove the spaces in the path folders (replace with "_" perhaps) and try again? I think that may be the causing factor. 

Best regards,
Miten

**Comment by nadakubikova** [comment]
Hi Miten,

Many thanks for you help, I really appreciate it. I tried again but this time I got a different error message.


(env) Nadas-MBP:marginAlign nadakubikova$ ./marginAlign /Users/nadakubikova/Documents/Sequenced\Data/fastq_First\Nanopore\Run/downloads/PASS/BC01/BC01_trimmed.fastq /Users/nadakubikova/Documents/Sequenced\Data/fastq_First\Nanopore\Run/downloads/PASS/BC01/chr1.fa /Users/nadakubikova/Documents/Sequenced\Data/fastq_First\Nanopore\Run/downloads/PASS/BC01/BC01_trimmed.sam --jobTree ./jobTree

The job seems to have left a log file, indicating failure: /Users/nadakubikova/marginAlign/jobTree/jobs/job

Reporting file: /Users/nadakubikova/marginAlign/jobTree/jobs/log.txt

log.txt:      ---JOBTREE SLAVE OUTPUT LOG---

log.txt:      Traceback (most recent call last):

log.txt:        File "/Users/nadakubikova/marginAlign/submodules/jobTree/src/jobTreeSlave.py", line 271, in main

log.txt:          defaultMemory=defaultMemory, defaultCpu=defaultCpu, depth=depth)

log.txt:        File "/Users/nadakubikova/marginAlign/submodules/jobTree/scriptTree/stack.py", line 153, in execute

log.txt:          self.target.run()

log.txt:        File "/Users/nadakubikova/marginAlign/src/margin/mappers/last.py", line 35, in run

log.txt:          Last.run(self)

log.txt:        File "/Users/nadakubikova/marginAlign/src/margin/mappers/last.py", line 11, in run

log.txt:          fH = open(self.outputSamFile, 'w')

log.txt:      IOError: [Errno 2] No such file or directory: '/Users/nadakubikova/Documents/SequencedData/fastq_FirstNanoporeRun/downloads/PASS/BC01/BC01_trimmed.sam'

log.txt:      Exiting the slave because of a failed job on host Nadas-MBP

log.txt:      Due to failure we are reducing the remaining retry count of job /Users/nadakubikova/marginAlign/jobTree/jobs/job to 0

log.txt:      We have set the default memory of the failed job to 2147483648.0 bytes

Job: /Users/nadakubikova/marginAlign/jobTree/jobs/job is completely failed

Traceback (most recent call last):

  File "./src/margin/marginAlign.py", line 109, in <module>

    main()

  File "/Users/nadakubikova/marginAlign/src/margin/marginAlign.py", line 105, in main

    raise RuntimeError("Got failed jobs")

RuntimeError: Got failed jobs

I am not sure what the path directory for the output file should be? I basically created the name I wanted the file to be saved as but I guess that wasn’t correct.

Best regards,
Nada

**Comment by mitenjain** [comment]
Hi Nada,

I think you will have to rename the folders themselves before you run marginAlign. Something like: 

./marginAlign /Users/nadakubikova/Documents/Sequenced_Data/fastq_First_Nanopore_Run/downloads/PASS/BC01/BC01_trimmed.fastq /Users/nadakubikova/Documents/Sequenced_Data/fastq_First_Nanopore_Run/downloads/PASS/BC01/chr1.fa /Users/nadakubikova/Documents/Sequenced_Data/fastq_First_Nanopore_Run/downloads/PASS/BC01/BC01_trimmed.sam --jobTree ./jobTree

Make sure you delete the jobTree folder before running again (rm -rf jobTree).

Hope this helps.
Best regards,
Miten

**Comment by nadakubikova** [comment]
Hi Miten,

Thanks again for your help. I tried the code below but got again the same error.


(env) Nadas-MBP:marginAlign nadakubikova$ ./marginAlign /Users/nadakubikova/Documents/Sequenced_Data/fastq_First_Nanopore_Run/downloads/PASS/BC01/BC01_trimmed.fastq /Users/nadakubikova/Documents/Sequenced_Data/fastq_First_Nanopore_Run/downloads/PASS/BC01/chr1.fa /Users/nadakubikova/Documents/Sequenced_Data/fastq_First_Nanopore_Run/downloads/PASS/BC01/BC01_trimmed.sam --jobTree ./jobTree

The job seems to have left a log file, indicating failure: /Users/nadakubikova/marginAlign/jobTree/jobs/job

Reporting file: /Users/nadakubikova/marginAlign/jobTree/jobs/log.txt

log.txt:      ---JOBTREE SLAVE OUTPUT LOG---

log.txt:      Traceback (most recent call last):

log.txt:        File "/Users/nadakubikova/marginAlign/submodules/jobTree/src/jobTreeSlave.py", line 271, in main

log.txt:          defaultMemory=defaultMemory, defaultCpu=defaultCpu, depth=depth)

log.txt:        File "/Users/nadakubikova/marginAlign/submodules/jobTree/scriptTree/stack.py", line 153, in execute

log.txt:          self.target.run()

log.txt:        File "/Users/nadakubikova/marginAlign/src/margin/mappers/last.py", line 35, in run

log.txt:          Last.run(self)

log.txt:        File "/Users/nadakubikova/marginAlign/src/margin/mappers/last.py", line 11, in run

log.txt:          fH = open(self.outputSamFile, 'w')

log.txt:      IOError: [Errno 2] No such file or directory: '/Users/nadakubikova/Documents/Sequenced_Data/fastq_First_Nanopore_Run/downloads/PASS/BC01/BC01_trimmed.sam'

log.txt:      Exiting the slave because of a failed job on host Nadas-MBP

log.txt:      Due to failure we are reducing the remaining retry count of job /Users/nadakubikova/marginAlign/jobTree/jobs/job to 0

log.txt:      We have set the default memory of the failed job to 2147483648.0 bytes

Job: /Users/nadakubikova/marginAlign/jobTree/jobs/job is completely failed

Traceback (most recent call last):

  File "./src/margin/marginAlign.py", line 109, in <module>

    main()

  File "/Users/nadakubikova/marginAlign/src/margin/marginAlign.py", line 105, in main

    raise RuntimeError("Got failed jobs")

RuntimeError: Got failed jobs

I think it doesn’t like the sam output. There is no such path or directory because I created the name for it but obviously I don’t have the sam file because that’s what I want marginAlign to create! I thought that this way I instruct it to make a file that will be named and stored acc to what I specify in the code?

Thanks a million! Best,
Nada

**Comment by nadakubikova** [comment]
Hi again Miten,

Just a quick update, I am finally running marginAlign :). It just didn’t like directories be named with more than 2 words I think so I renamed the files and it seems to have worked. Fingers crossed!

Best,
Nada

From: Nada Kubikova <nada.kubikova@bnc.ox.ac.uk>
Date: Tuesday, 11 September 2018 at 09:27
To: benedictpaten/marginAlign <reply@reply.github.com>
Subject: Re: [benedictpaten/marginAlign] RuntimeError - "expected three arguments" (#44)

Hi Miten,

Thanks again for your help. I tried the code below but got again the same error.


(env) Nadas-MBP:marginAlign nadakubikova$ ./marginAlign /Users/nadakubikova/Documents/Sequenced_Data/fastq_First_Nanopore_Run/downloads/PASS/BC01/BC01_trimmed.fastq /Users/nadakubikova/Documents/Sequenced_Data/fastq_First_Nanopore_Run/downloads/PASS/BC01/chr1.fa /Users/nadakubikova/Documents/Sequenced_Data/fastq_First_Nanopore_Run/downloads/PASS/BC01/BC01_trimmed.sam --jobTree ./jobTree

The job seems to have left a log file, indicating failure: /Users/nadakubikova/marginAlign/jobTree/jobs/job

Reporting file: /Users/nadakubikova/marginAlign/jobTree/jobs/log.txt

log.txt:      ---JOBTREE SLAVE OUTPUT LOG---

log.txt:      Traceback (most recent call last):

log.txt:        File "/Users/nadakubikova/marginAlign/submodules/jobTree/src/jobTreeSlave.py", line 271, in main

log.txt:          defaultMemory=defaultMemory, defaultCpu=defaultCpu, depth=depth)

log.txt:        File "/Users/nadakubikova/marginAlign/submodules/jobTree/scriptTree/stack.py", line 153, in execute

log.txt:          self.target.run()

log.txt:        File "/Users/nadakubikova/marginAlign/src/margin/mappers/last.py", line 35, in run

log.txt:          Last.run(self)

log.txt:        File "/Users/nadakubikova/marginAlign/src/margin/mappers/last.py", line 11, in run

log.txt:          fH = open(self.outputSamFile, 'w')

log.txt:      IOError: [Errno 2] No such file or directory: '/Users/nadakubikova/Documents/Sequenced_Data/fastq_First_Nanopore_Run/downloads/PASS/BC01/BC01_trimmed.sam'

log.txt:      Exiting the slave because of a failed job on host Nadas-MBP

log.txt:      Due to failure we are reducing the remaining retry count of job /Users/nadakubikova/marginAlign/jobTree/jobs/job to 0

log.txt:      We have set the default memory of the failed job to 2147483648.0 bytes

Job: /Users/nadakubikova/marginAlign/jobTree/jobs/job is completely failed

Traceback (most recent call last):

  File "./src/margin/marginAlign.py", line 109, in <module>

    main()

  File "/Users/nadakubikova/marginAlign/src/margin/marginAlign.py", line 105, in main

    raise RuntimeError("Got failed jobs")

RuntimeError: Got failed jobs

I think it doesn’t like the sam output. There is no such path or directory because I created the name for it but obviously I don’t have the sam file because that’s what I want marginAlign to create! I thought that this way I instruct it to make a file that will be named and stored acc to what I specify in the code?

Thanks a million! Best,
Nada
