### ISSUE TITLE
Segmentation fault error when there are two references

### ISSUE THREAD

**Issue by mitenjain** [benedictpaten/marginAlign#6]
---JOBTREE SLAVE OUTPUT LOG---
/bin/sh: line 1: 24546 Done                    echo cigar: channel_439_read_57 0 1122 + DNA_CS 0 3
559 + 1 D 1838 I 1 M 7 D 1 M 3 I 2 M 6 D 1 M 13 I 1 M 2 I 1 M 7 I 1 M 16 D 1 M 35 D 1 M 47 I 1 M 1
 I 2 M 11 D 3 M 45 I 2 M 26 I 1 M 2 I 1 M 18 D 2 M 17 I 1 M 36 D 2 M 4 D 1 M 8 I 2 M 7 D 1 M 9 I 1
 M 52 D 1 M 8 D 1 M 9 D 3 M 29 D 1 M 18 D 3 M 12 D 1 M 19 I 2 M 103 D 1 M 18 D 1 M 8 D 1 M 14 I 1 
M 9 D 1 M 10 I 1 M 3 D 1 M 5 D 1 M 9 I 2 M 14 D 1 M 14 D 1 M 2 I 1 M 4 I 1 M 46 D 1 M 2 I 1 M 66 I
 1 M 1 I 1 M 17 I 2 M 5 D 1 M 20 I 1 M 12 D 1 M 71 I 1 M 15 I 2 M 9 D 2 M 23 I 1 M 6 D 1 M 6 D 1 M
 6 D 1 M 19 D 2 M 26 I 1 M 36 I 1 M 9 D 605 I 10
     24547 Segmentation fault      (core dumped) | cPecanRealign /scratch/tmp/tmpivbY_w/localTempD
ir/ref.fa /scratch/tmp/tmpivbY_w/localTempDir/read.fa --diagonalExpansion=10 --splitMatrixBiggerTh
anThis=3000 --loadHmm /hive/users/miten/pipeline_full_runs/stats_marginAlign/margin/src/margin/map
pers/last_hmm_20.txt --gapGamma=0.5 --matchGamma=0.0 >> /hive/users/miten/pipeline_full_runs/stats
_marginAlign/margin/jobTreeM13NoEM/jobs/gTD1/tmp_zsbGhgPBdH/tempOutput_1814.txt
Traceback (most recent call last):
  File "/hive/users/miten/pipeline_full_runs/stats_marginAlign/margin/submodules/jobTree/src/jobTr
eeSlave.py", line 271, in main
    defaultMemory=defaultMemory, defaultCpu=defaultCpu, depth=depth)
  File "/hive/users/miten/pipeline_full_runs/stats_marginAlign/margin/submodules/jobTree/scriptTre
e/stack.py", line 153, in execute
    self.target.run()
  File "/hive/users/miten/pipeline_full_runs/stats_marginAlign/margin/submodules/jobTree/scriptTre
e/target.py", line 197, in run
    func(_((self,) + tuple(self.args)), *_self.kwargs)
  File "/hive/users/miten/pipeline_full_runs/stats_marginAlign/margin/src/margin/marginAlignLib.py
", line 319, in realignCigarTargetFn
    options.gapGamma, options.matchGamma, outputCigarFile))
  File "/hive/users/miten/pipeline_full_runs/stats_marginAlign/margin/submodules/sonLib/bioio.py",
 line 184, in system
    raise RuntimeError("Command: %s exited with non-zero status %i" % (command, sts))
RuntimeError: Command: echo cigar: channel_439_read_57 0 1122 + DNA_CS 0 3559 + 1 D 1838 I 1 M 7 D
 1 M 3 I 2 M 6 D 1 M 13 I 1 M 2 I 1 M 7 I 1 M 16 D 1 M 35 D 1 M 47 I 1 M 1 I 2 M 11 D 3 M 45 I 2 M
 26 I 1 M 2 I 1 M 18 D 2 M 17 I 1 M 36 D 2 M 4 D 1 M 8 I 2 M 7 D 1 M 9 I 1 M 52 D 1 M 8 D 1 M 9 D 
3 M 29 D 1 M 18 D 3 M 12 D 1 M 19 I 2 M 103 D 1 M 18 D 1 M 8 D 1 M 14 I 1 M 9 D 1 M 10 I 1 M 3 D 1
 M 5 D 1 M 9 I 2 M 14 D 1 M 14 D 1 M 2 I 1 M 4 I 1 M 46 D 1 M 2 I 1 M 66 I 1 M 1 I 1 M 17 I 2 M 5 
D 1 M 20 I 1 M 12 D 1 M 71 I 1 M 15 I 2 M 9 D 2 M 23 I 1 M 6 D 1 M 6 D 1 M 6 D 1 M 19 D 2 M 26 I 1
 M 36 I 1 M 9 D 605 I 10 | cPecanRealign /scratch/tmp/tmpivbY_w/localTempDir/ref.fa /scratch/tmp/t
mpivbY_w/localTempDir/read.fa --diagonalExpansion=10         --splitMatrixBiggerThanThis=3000 --lo
adHmm /hive/users/miten/pipeline_full_runs/stats_marginAlign/margin/src/margin/mappers/last_hmm_20
.txt --gapGamma=0.5 --matchGamma=0.0 >> /hive/users/miten/pipeline_full_runs/stats_marginAlign/mar
gin/jobTreeM13NoEM/jobs/gTD1/tmp_zsbGhgPBdH/tempOutput_1814.txt exited with non-zero status 139
Exiting the slave because of a failed job on host juggernaut
Due to failure we are reducing the remaining retry count of job /hive/users/miten/pipeline_full_ru
ns/stats_marginAlign/margin/jobTreeM13NoEM/jobs/t3/t3/t3/t4/t2/t0/job to 0
We have set the default memory of the failed job to 2147483648 bytes

**Comment by benedictpaten** [comment]
Hi Miten,

Is this for marginAlign, marginCall or both?

**Comment by mitenjain** [comment]
Hi Ben,

I have not checked this for marginCall. I can check it right now and get
back to you in a few minutes.

Best regards,
Miten

**Comment by benedictpaten** [comment]
What would be most helpful would be if you could add a test to the unit-tests that has two references for marginAlign. That way I can fix this and we'll know it's fixed in future revisions.

**Comment by mitenjain** [comment]
Sure. I will do it ASAP.

**Comment by benedictpaten** [comment]
Just pushed a fix - I note that some tests fail because the file "./tests/input2Refs.sam" is not in the repo.. possibly forgot to commit?

**Comment by mitenjain** [comment]
Committed. Sorry for forgetting earlier.

All tests working now.

**Comment by benedictpaten** [comment]
Great, I'm working on the local alignment vs. global alignment issue.
