### ISSUE TITLE
Assembly hub (changing realignment from global to local)

### ISSUE THREAD

**Issue by mitenjain** [benedictpaten/marginAlign#7]
link to hub: http://hgwdev.soe.ucsc.edu/~miten/ecoli_hub/hub.txt
link to assembly hub on browser: http://genome.ucsc.edu/cgi-bin/hgTracks?hgS_doOtherUser=submit&hgS_otherUserName=miten&hgS_otherUserSessionName=Test_hub_40127_E.coli_K12
link to hub on hgwdev: /cluster/home/miten/public_html/ecoli_hub

**Comment by benedictpaten** [comment]
Fixed on localCoordinates branch - but needs testing. Will close this issue when testing complete and pushed to master.

**Comment by mitenjain** [comment]
Utility to create Assembly Hub done. To be tested on E. coli data shortly.

**Comment by benedictpaten** [comment]
Miten - please test.

**Comment by mitenjain** [comment]
Tested successfully on 10 E.coli test reads (lengths up to 11 kb).
